//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Orders()
        {
            this.Book_Order_Details = new HashSet<Book_Order_Details>();
            this.Book_Payment = new HashSet<Book_Payment>();
        }
    
        public int Order_id { get; set; }
        public int Customer_id_fk { get; set; }
        public int order_Status_id_fk { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
        public string Shipping_Address { get; set; }
        public string Shipping_Method { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Order_Details> Book_Order_Details { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Order_Status Order_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Payment> Book_Payment { get; set; }
    }
}
