//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books_Category
    {
        public int Category_id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Lastupdated { get; set; }
        public int Number_of_books { get; set; }
        public int admin_id_fk { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
