//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Payment
    {
        public int Pay_id { get; set; }
        public int Books_Order_id_fk { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public double Amount { get; set; }
        public string Method { get; set; }
    
        public virtual Book_Orders Book_Orders { get; set; }
    }
}
