//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Order_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Order_Details()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int Order_det_id { get; set; }
        public int Book_id_fk { get; set; }
        public int Book_order_id_fk { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
        public int Quantity { get; set; }
        public double Unit_Price { get; set; }
    
        public virtual Book_Orders Book_Orders { get; set; }
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
